# Generated by Django 5.1.4 on 2025-11-02 05:54

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
        ('users', '0004_alter_user_options_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('text_content', models.TextField(blank=True, help_text='Extracted text from PDF page')),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio')),
                ('audio_duration', models.IntegerField(default=0, help_text='Audio duration in seconds')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_pages',
                'ordering': ['book', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='ListeningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1, help_text='Last page listened to')),
                ('current_position', models.IntegerField(default=0, help_text='Position in current page audio (seconds)')),
                ('total_listened_time', models.IntegerField(default=0, help_text='Total time listened in seconds')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Percentage of book completed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_listened_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'listening_progress',
                'ordering': ['-last_listened_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='User notes about the book', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('favorited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_library',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('literature', 'Literature'), ('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('biography', 'Biography'), ('history', 'History'), ('science', 'Science'), ('philosophy', 'Philosophy'), ('religion', 'Religion'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('urdu', 'Urdu'), ('bengali', 'Bengali'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('marathi', 'Marathi'), ('gujarati', 'Gujarati'), ('other', 'Other')], default='hindi', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='listen_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_progress',
            field=models.IntegerField(default=0, help_text='Percentage of pages processed'),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='total_duration',
            field=models.IntegerField(default=0, help_text='Total audio duration in seconds'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdfs'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['uploader', 'is_public'], name='books_uploade_3b5014_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language', 'is_public'], name='books_languag_b2117e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre', 'is_public'], name='books_genre_e02551_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['processing_status'], name='books_process_dd2069_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-uploaded_at'], name='books_uploade_9b2f28_idx'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AddField(
            model_name='bookpage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='audiobooks.book'),
        ),
        migrations.AddField(
            model_name='listeningprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='audiobooks.book'),
        ),
        migrations.AddField(
            model_name='listeningprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_progress', to='users.user'),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_libraries', to='audiobooks.book'),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['book', 'page_number'], name='book_pages_book_id_f7ba84_idx'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['processing_status'], name='book_pages_process_8a986d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookpage',
            unique_together={('book', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='listeningprogress',
            index=models.Index(fields=['user', '-last_listened_at'], name='listening_p_user_id_e91071_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningprogress',
            index=models.Index(fields=['user', 'is_completed'], name='listening_p_user_id_aefb6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listeningprogress',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['user', 'is_favorite'], name='user_librar_user_id_407ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['user', '-added_at'], name='user_librar_user_id_2714f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('user', 'book')},
        ),
    ]
