// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnggqmkkeknclrmyifmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZ2dxbWtrZWtuY2xybXlpZm10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTA2NzEsImV4cCI6MjA2MzU4NjY3MX0.1hn_KwaWZgZa3n4xtPiKmLGFlbokyksalBG6Opa4EL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);